name: Daily Web Scraper

on:
  schedule:
    - cron: '30 12 * * *'  # runs daily at 6:00 PM IST (converted to UTC)
  workflow_dispatch:       # allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy

    - name: Run scraping script
      run: python bankrate_loans.py
